version: '3.8'

services:
  oasfi:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./output_csv:/app/output_csv  # CSVの出力先をマウント
    command: >
      /app/oasfi export-staker-reward
      0x272d6bd040c2b8454f4f6f43115758fbe318ee2c,0x4e5e774d3837bd9302b83cad94a112575411f07b
      --from_date=2023-01-04T10:00:00
      --to_date=2024-01-16T10:00:00
      --output=/app/output_csv/test.csv 