version: '3.8'

services:
  oasfi_singapore:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./output_csv:/app/output_csv  # Mount the output CSV directory
    command: >
      /app/oasfi export-staker-reward
      0x272d6bd040c2b8454f4f6f43115758fbe318ee2c,0x4e5e774d3837bd9302b83cad94a112575411f07b
      --from_date=2024-11-11T10:00:00
      --to_date=2025-01-16T10:00:00
      --time_zone=Asia/Singapore
      --output=/app/output_csv/staker-reward_Singapore.csv

  oasfi_newyork:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./output_csv:/app/output_csv  # Mount the output CSV directory
    command: >
      /app/oasfi export-staker-reward
      0x272d6bd040c2b8454f4f6f43115758fbe318ee2c,0x4e5e774d3837bd9302b83cad94a112575411f07b
      --from_date=2024-11-11T10:00:00
      --to_date=2025-01-16T10:00:00
      --time_zone=America/New_York
      --output=/app/output_csv/staker-reward_NewYork.csv
