name: Release Workflow

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Create Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important: This is needed to fetch all tags

      - name: Bump version and push tag
        id: create_tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: main
          DEFAULT_BUMP: patch

      - name: Check out new tag
        run: |
          echo "New tag created: ${{ steps.create_tag.outputs.tag }}"

      - name: Save the tag
        run: |
          echo "${{ steps.create_tag.outputs.tag }}" > tag.txt    

      - name: Upload tag as artifact
        uses: actions/upload-artifact@v3
        with:
          name: tag
          path: tag.txt

  prepare-release:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      new_tag: ${{ steps.set_tag.outputs.tag }}  # Updated this line to use the set_tag step

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download tag artifact
      uses: actions/download-artifact@v3
      with:
        name: tag

    - name: Set the tag
      id: set_tag
      run: |
        TAG=$(cat tag.txt)
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Use computed tag
      run: |
        echo "Next tag will be: ${{ steps.set_tag.outputs.tag }}"  # Updated this line to use the set_tag step


  build-and-release:
    needs: prepare-release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Build with pkg
      run: |
        npm i
        jq '.version = "${{ needs.prepare-release.outputs.new_tag }}"' src/config.json > src/config_temp.json && mv src/config_temp.json src/config.json
        npx tsc
        npm install -g pkg
        pkg . -t node18-linux-x64 --output ./oasfi-linux
        pkg . -t node18-macos-x64 --output ./oasfi-macos
        pkg . -t node18-win-x64 --output ./oasfi-win.exe

    - name: Create GitHub Release and Upload binaries/source
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ needs.prepare-release.outputs.new_tag }}
        files: |
          ./oasfi-linux,
          ./oasfi-macos,
          ./oasfi-win.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
